### ISSUE TITLE
Metrics and graphics under menu button Nõustajad (CSAs)

### ISSUE THREAD

**Issue by PaulaMerle** [buerokratt/Analytics-Module#10]
AS AN Analytic module user
I WANT TO have predefined chat-related metrics under Nõustajad
SO THAT I can visualize them easily by clicking on the desired metric.

### Acceptance Criteria

**General requirements**

- [ ] A separate sub-page for chat-specific analytics on GUI-side
- [ ] Appropriate graph displayed according to selected metric and periods
- [ ] When selected period is 1 day (today, yesterday or from calendar), the chart is displayed on hourly bases
- [ ] #6 is taken into consideration
- [ ] Chosen selection of metrics can be downloaded as CSV - https://github.com/buerokratt/Analytics-Module/issues/14

**User selections for graphics to be shown**

 - [ ] Menu button Nõustajad is highlighted
 - [ ] Three drop-down menus available as shown on prototype:
-- vali mõõdik -- (choose metric)
-- lisavalikud -- (additional options)
-- vali periood -- (choose period)
- [ ] options in -- choose metric --:
1. Chat forwards (Suunamised)
2. average time of picking up the chat (Keskmine vastamise kiirus asutuses)
3. average number of CSAs being present (Keskmine nõustajate kohalolu)
4. number of chats by CSAs (Vestluste arv nõustaja lõikes)
5. average chat time by CSAs (Vestluste aeg nõustaja lõikes)
 - [ ] options in -- lisavalikud -- for Suunamised:
1. number of forwarded chats from the CSA (Nõustajalt suunatud vestluste arv)
2. number of chats forwarded to CSA (Nõustajale suunatud vestluste arv)
3. number of chats forwarded to other organisation (Suunamised asutusest välja)
 - [ ] options in -- vali periood --:
1. today (Täna)
2. yesterday (Eile)
3. last 30 days (Viimased 30 päeva)
4. selected months - from datepicker or any other possibility (Valitud kuud)
5. selected period - from datepicker (Valitud periood kalendrist)
 - [ ] appropriate graph displayed according to selected metric and periods
 - [ ] when selected period is 1 day (today, yesterday or from calendar), the chart is displayed on hourly bases
 - [ ]  https://github.com/buerokratt/Analytics-Module/issues/6 is taken into consideration

![Image](https://user-images.githubusercontent.com/56122140/187183909-61aa3242-78e5-4945-b83f-951c1093f793.png)

#### Technical AC

- [ ] #34
- [ ] #35

**Comment by turnerrainer** [comment]
These predefined selections currently all have corresponding matches in a PostgreSQL database.
