### ISSUE TITLE
Changes in Analytics Module

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Analytics-Module#324]
AS AN Analyst
I WANT TO see only completed conversations in the analytics module and ensure that the total number of conversations displayed in the module reflects the time period or date selected by me and counts conversations for graph's legend
SO THAT I can easily analyze the data for a specific period and see the conversation count for each condition in the graph's legend

### Acceptance criteria

- [ ] buerokratt/Buerokratt-Chatbot#917
- [ ] buerokratt/Buerokratt-Chatbot#918
- [ ] buerokratt/Buerokratt-Chatbot#919
- [ ] buerokratt/Buerokratt-Chatbot#920
- [ ] buerokratt/Buerokratt-Chatbot#921
- [ ] buerokratt/Buerokratt-Chatbot#922
- [ ] buerokratt/Buerokratt-Chatbot#923
- [ ] buerokratt/Buerokratt-Chatbot#924
- [ ] buerokratt/Buerokratt-Chatbot#925
- [ ] buerokratt/Buerokratt-Chatbot#926
- [ ] buerokratt/Buerokratt-Chatbot#927
- [ ] buerokratt/Buerokratt-Chatbot#928

**Comment by rasmusei** [comment]
All subtasks have been completed
