### ISSUE TITLE
Metrics and graphics under menu button Bürokratt

### ISSUE THREAD

**Issue by PaulaMerle** [buerokratt/Analytics-Module#8]
**HIDE FOR RELEASE 2.0 AND PROCEED LATER**

AS AN Analytic module user
I WANT TO have predefined chat-related metrics under Bürokratt
SO THAT I can visualize them easily by clicking on the desired metric.

### Acceptance Criteria

**General requirements**

- [x] A separate sub-page for chat-specific analytics on GUI-side
- [ ] Appropriate graph displayed according to selected metric and periods
- [x] When selected period is 1 day (today, yesterday or from calendar), the chart is displayed on hourly bases
- [x] #6 is taken into consideration
- [x] Chosen selection of metrics can be downloaded as CSV - https://github.com/buerokratt/Analytics-Module/issues/14

**User selections for graphics to be shown**

- [x] Menu button Bürokratt is highlighted
- [x] Three drop-down menus available as shown on prototype:
1. -- vali mõõdik -- (choose metric)
2. -- lisavalikud -- (additional options)
3. -- vali periood -- (choose period)
- [x] options in -- choose metric --:
1. intents (Teemad)
2. Sessioonid (sessions)
3. byk average response speed (Bürokrati keskmine vastamise kiirus)
4. percentage of questions correctly understood by the byk (Õigesti mõistetud küsimuste %)
- [x] additional options with tickbox for Intents:
1. order of intents by usability (Teemad kasutatavuse järgi)
2. new intents (Uued treenitud teemad)
3. modified intents (Muudetud teemad)
4. average number of intents in a chat (Keskmine tuvastatud teemade arv ühes vestluses)
- [x] additional options with tickbox for Sessions:
1. average time of session when CSA involved (Keskmine aeg, Bürokratt + nõustaja)
2. average time of session with only Bürokratt involved, incl closed by Bürokratt (idle sessions) (Keskmine aeg, ainult Bürokratt) 
3. average time of session, closed by customer (Keskmine aeg Bürokratiga, kliendi lõpetatud)
- [x] options in -- vali periood --:
1. today (Täna)
2. yesterday (Eile)
3. last 30 days (Viimased 30 päeva)
4. selected months - from datepicker or any other possibility (Valitud kuud)
5. selected period - from datepicker (Valitud periood kalendrist)
- [x] appropriate graph displayed according to selected metric and periods
- [x] when selected period is 1 day (today, yesterday or from calendar), the chart is displayed on hourly bases
- [x] https://github.com/buerokratt/Analytics-Module/issues/6 is taken into consideration

![Image](https://user-images.githubusercontent.com/56122140/187157989-c7249f02-a38c-44ac-878c-c7f843a57739.png)

#### GUI

- [ ] `i18n` used
- [ ] Dropdown values as pre-defined configurable settings, no database used
- [ ] Choose from [D3 library](https://d3js.org) and https://canvasjs.com/react-charts/ to produce graphs
- [ ] Make REST requests to fetch appropriate data to produce graphs based on User's current selection

##### General agreements

- [ ] Ruuter REST endpoints to produce data for every metric
- [ ] REST endpoints as CSV, use Handlebars DSLs or Javascript on Nodejs for chosen metrics provided in CSV instead of JSON, applies on all REST endpoints in the scope of this issue

##### REST services

- [x] #39

**Comment by turnerrainer** [comment]
These predefined selections currently all have corresponding matches in a PostgreSQL database.

**Comment by baha-a** [comment]
Blocked because `intents` data is not available currently according to [issue #29](https://github.com/buerokratt/Analytics-Module/issues/29) & [this comment](https://github.com/buerokratt/Analytics-Module/issues/17#issuecomment-1383931020).

**Comment by PaulaMerle** [comment]
Please hide this page for release 2.0, will be taken into work later.

**Comment by 1AhmedYasser** [comment]
@ExiRain Could you please remove `/burokratt` from menu and add a new version

**Comment by ExiRain** [comment]
Updated menu package to v0.1.4 with changes.
Also[ PR ](https://github.com/buerokratt/sample-implementation-cvi/pull/19)under simple cvi implementation
